### ISSUE TITLE
The icon is broken.

### ISSUE THREAD

**Issue by K0-RR** [Blobanium/Loading-Timer#31] opened 2021-07-31 12:44 UTC
![image](https://user-images.githubusercontent.com/43277609/127740239-5b6221fa-5682-4978-9b07-4a79540f4633.png)
https://github.com/Blobanium/Loading-Timer/blob/1.17/src/main/resources/assets/lt/icon.png

**Comment by K0-RR** [comment] 2021-07-31 12:50
I did this:
![Screenshot from 2021-07-31 14-48-54](https://user-images.githubusercontent.com/43277609/127740372-9385cdb9-b412-4eec-a69a-00e91a6b8d5e.png)

It's kinda better because it's readable but...

IMG:
![Logo](https://user-images.githubusercontent.com/43277609/127740384-2f1c2e12-7dc6-45f9-b753-650fd222341f.png)

**Comment by Blobanium** [comment] 2021-08-05 21:18
what did u do to reproduce this, it looks like its completely fine on my end

**Comment by srnyx** [comment] 2021-12-17 20:06
> what did u do to reproduce this, it looks like its completely fine on my end

Happens to me as well
Reproduction (using GDLauncher):
1. Create a new Fabric 1.17.1 instance
2. Add Loading Timer
3. Add Fabric API
3. Add Mod Menu
4. Launch the game
5. Click `Mods` button
6. Observe icon

**Comment by egeesin** [comment] 2022-01-09 15:01
If the pack icon is based on non-square image, rendering options may differ on different platforms. The icon in the Modrinth page is also seems like it's "stretched to fit". It's better to convert the source image to square. (128x128px I assume?)

Also author should have notified that there's a placeholder icon in [here](https://github.com/Blobanium/Loading-Timer/blob/1.18/src/main/resources/assets/lt/icon.png) now, there's no reason to keep this issue open.

**Comment by srnyx** [comment] 2022-01-09 15:22
> there's no reason to keep this issue open.

Well, the icon isn't being used, so the issue still persists. Until it's fixed I think the issue should stay open.

**Comment by Blobanium** [comment] 2022-01-09 18:34
Issue should be fixed in commit fc2b695, reopen if issue still persists

**Closed as completed by Blobanium** 2022-01-09 18:34 UTC
