### ISSUE TITLE
Is it counting properly? (Conflicts With Architectury API)

### ISSUE THREAD

**Issue by K0-RR** [Blobanium/Loading-Timer#10] opened 2021-03-06 23:22 UTC
Look at the values of "raw loading time", the second image vs the rest of them. Also, the 4th and 5th have the same "raw" how?
![image](https://user-images.githubusercontent.com/43277609/110224100-031a7280-7ed9-11eb-9cc9-d3a5de62993f.png)
![image](https://user-images.githubusercontent.com/43277609/110224104-0877bd00-7ed9-11eb-90e8-24fa31b4ea99.png)
![image](https://user-images.githubusercontent.com/43277609/110224305-a3bd6200-7eda-11eb-831a-2b668e252e09.png)
![image](https://user-images.githubusercontent.com/43277609/110224321-b768c880-7eda-11eb-8027-d8e19f370b43.png)
![image](https://user-images.githubusercontent.com/43277609/110224342-f434bf80-7eda-11eb-9602-34ec7944ba43.png)

**Comment by Blobanium** [comment] 2021-03-07 00:35
The second result is most likely correct, for the others I don't really know what's causing this.. (resource packs maybe? or maybe some other mod? who knows?). 

And for the 4th and 5th "raw" times, "Raw loading time" is usually defined by taking how much time it usually takes to load and then subtracting it by how much it took to initialize, or defined by [this line](https://github.com/Blobanium/Loading-Timer/blob/3134affe3f43f4cfae6de78d8cb58933769dfac1/src/main/java/io/github/blobanium/lt/LoadingTimer.java#L59). Assuming you got 31.89 seconds and 32.078 seconds If initialization time respectively then this is probably not a real issue.

**Comment by Blobanium** [comment] 2021-03-07 00:39
also i might need to make it so that the "raw" values are rounded and not like if they have so many decimal points(if you really know what i mean).

**Comment by Blobanium** [comment] 2021-03-07 00:44
Adding the label as "question" for now, if this is an actual bug then probably add the "bug" label as well.

**Comment by K0-RR** [comment] 2021-03-07 14:08
I updated to 1.2.1 and I'm not using a resource pack
![image](https://user-images.githubusercontent.com/43277609/110242490-b37a8c00-7f56-11eb-8d08-3278667b5288.png)
This may be a mod conflict because now I only get these "low raw times" and before adding some mods the values were correct.

**Comment by Blobanium** [comment] 2021-03-07 20:26
Huh weird do you know of any mods that could be messing with the raw times?

**Comment by K0-RR** [comment] 2021-03-07 21:44
Found the conflicting mod - Architectury

**Comment by Blobanium** [comment] 2021-03-07 22:00
Confirmed With v1.7.117 and v1.8.131

**Comment by Blobanium** [comment] 2021-03-07 22:38
ill try looking into architectury and see what i can do.

**Comment by Blobanium** [comment] 2021-03-08 01:05
i opened an issue on archetectury api's github because i suspect this is on their end, but i wanna make sure first.

**Comment by Felix14-v2** [comment] 2021-03-09 12:56
I noticed a similar problem caused by architectury:
https://youtu.be/8kg8HgqLKoo

UPD: Here's another problem with counting:
https://youtu.be/Gn1lVT4R7k0

**Comment by Blobanium** [comment] 2021-03-09 21:34
i pushed a commit that could fix this issue, can you test and make sure its working properly now?

**Comment by K0-RR** [comment] 2021-03-09 22:49
I must say it's building quite long (9 minutes) for such a small mod, Unearthed and Sodium are building about two minutes for me. **Seems to be working**
![image](https://user-images.githubusercontent.com/43277609/110549278-1d9b5880-8132-11eb-8d0f-56eb27d3254f.png)

**Comment by K0-RR** [comment] 2021-03-09 22:58
To be clear, toasts after saving a world and going to the settings are fixed too but why didn't you tested this by yourself? Don't get me wrong I like testing commits and reporting if something is wrong I just thought this bug was "global" - for all users of your mod.
Can I ask you another question? How long you had to learn java and modding to be able to make this mod?

**Comment by Blobanium** [comment] 2021-03-10 00:41
i did test out this mod when i was making it using "gradlew runClient," i really wanted you guys to also test it out just to make sure it was fixed on your end also. 

And answering your second question, probably about 2-3 days to make this mod (if that's what your talking about).

**Comment by Blobanium** [comment] 2021-03-10 01:27
also this issue is ready to be closed as this issue has has been fixed so closing this issue now..

**Closed as completed by Blobanium** 2021-03-10 01:27 UTC
Labels: bug, mod conflict
