### ISSUE TITLE
Doesn't work when Minecraft is set to fullscreen mode.

### ISSUE THREAD

**Issue by K0-RR** [Blobanium/Loading-Timer#9] opened 2021-03-06 15:29 UTC
Weird this screenshot is broken. I will try to get a new one but the toast shows up when Minecraft is still loading and the text is broken.

**Comment by K0-RR** [comment] 2021-03-06 15:47
Not possible to provide a screenshot because every time it's broken for some reason... Will try to record this if you can't reproduce it.

**Comment by Blobanium** [comment] 2021-03-06 16:59
Tried Reproducing, so it seems like for me its calling the toast is being called way too early. ill look into this

**Comment by Blobanium** [comment] 2021-03-06 20:31
I can give an explanation if i can (i kind of suck at explaining things so ill try my best to explain this): This mod relies on using [Title Screen](https://github.com/Blobanium/Loading-Timer/blob/5a0d00383c188967cf83fe73882d026aa5bdcab2/src/main/java/io/github/blobanium/lt/mixin/LoadModMixin.java#L11) to call the [Load method](https://github.com/Blobanium/Loading-Timer/blob/5a0d00383c188967cf83fe73882d026aa5bdcab2/src/main/java/io/github/blobanium/lt/LoadingTimer.java#L34). During startup in my testing when i was making this mod, this method only calls two times, so i only set this to only call two times ([#1 should explain why i did this](https://github.com/Blobanium/Loading-Timer/issues/1)). But somehow when its in full screen mode, it calls that same method four times during startup instead of two. i probably have a workarround for this.

**Comment by Blobanium** [comment] 2021-03-06 22:48
This should be fixed, if you have any other issues, please open another issue thread, thanks.

**Closed as completed by Blobanium** 2021-03-06 22:48 UTC
Labels: bug

**Comment by K0-RR** [comment] 2021-03-07 18:12
![image](https://user-images.githubusercontent.com/43277609/110249481-86d66c80-7f76-11eb-9b14-e4a3578390e2.png)
I wasn't going in or out of fullscreen. This showed up when I saved my world

**Comment by Blobanium** [comment] 2021-03-07 20:49
thats odd, do you have the log, because i have it set to print a stacktrace see whats happening, also this happened way after startup, right?

**Comment by Blobanium** [comment] 2021-03-07 21:18
never mind i think i found the fix, turns out the problem seemed to be that if the control variable ["hasGameStarted"](https://github.com/Blobanium/Loading-Timer/blob/16825b1c2e8952bfebc871a6db636e85659655ed/src/main/java/io/github/blobanium/lt/LoadingTimer.java#L67) is 2, then every time it shows the title screen it might kick that message. probably a very easy fix

**Comment by K0-RR** [comment] 2021-03-07 21:18
![image](https://user-images.githubusercontent.com/43277609/110255224-e80c3900-7f92-11eb-8bb9-1e73c2735433.png)
Ok so I started mc and didn't resize it, got the toast then go to the singleplayer and returned back and saw this

**Comment by K0-RR** [comment] 2021-03-07 21:19
> never mind i think i found the fix, turns out the problem seemed to be that if the control variable ["hasGameStarted"](https://github.com/Blobanium/Loading-Timer/blob/16825b1c2e8952bfebc871a6db636e85659655ed/src/main/java/io/github/blobanium/lt/LoadingTimer.java#L67) is 2, then every time it shows the title screen it might kick that message. probably a very easy fix

oh

**Comment by Blobanium** [comment] 2021-03-07 21:20
i should be rolling out an easy fix right now

**Comment by K0-RR** [comment] 2021-03-07 21:26
This happens when you maximalize mc when it's loading
![image](https://user-images.githubusercontent.com/43277609/110255465-281feb80-7f94-11eb-849f-3b6977389fc0.png)

**Comment by K0-RR** [comment] 2021-03-07 21:27
[22:25:46] [main/INFO]: [STDERR]: The user toggled full screen during startup
[22:25:46] [main/INFO]: [STDERR]: java.lang.Exception: Stack trace
[22:25:46] [main/INFO]: [STDERR]: 	at java.lang.Thread.dumpStack(Thread.java:1336)
[22:25:46] [main/INFO]: [STDERR]: 	at io.github.blobanium.lt.LoadingTimer.load(LoadingTimer.java:75)
[22:25:46] [main/INFO]: [STDERR]: 	at net.minecraft.class_442.handler$zic005$init(class_442.java:516)
[22:25:46] [main/INFO]: [STDERR]: 	at net.minecraft.class_442.method_25426(class_442.java)
[22:25:46] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25423(class_437.java:325)
[22:25:46] [main/INFO]: [STDERR]: 	at net.minecraft.class_425.method_25394(class_425.java:139)
[22:25:46] [main/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:605)
[22:25:46] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1048)
[22:25:46] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:681)
[22:25:46] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[22:25:46] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:25:46] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:25:46] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:25:46] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:25:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[22:25:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
[22:25:46] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[22:25:46] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:25:46] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:25:46] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:25:46] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:25:46] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[22:25:46] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[22:25:46] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[22:25:46] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)



I didn't enter fullscreen, only maximalized.

**Comment by K0-RR** [comment] 2021-03-07 21:29
It's even better when you maximalize and then unmaximalize

**Comment by K0-RR** [comment] 2021-03-07 21:31
![image](https://user-images.githubusercontent.com/43277609/110255591-d1ff7800-7f94-11eb-838f-7c970f4c2df8.png)
So it fully loaded, then I maximalized and god notification about going into fullscreen when mc is loading

**Comment by Blobanium** [comment] 2021-03-07 21:33
i probably should move this to another issue thread, as this is probably more resembling another issue. (#11 )
